version: '3.8'

services:
  app:
    build: .
    container_name: desafio-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=desafio_db
      - GIN_MODE=debug
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - db
    networks:
      - desafio-network

  db:
    image: mysql:8.0
    container_name: desafio-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: desafio_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./setup_db.sh:/docker-entrypoint-initdb.d/setup_db.sh
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: bridge

volumes:
  mysql_data:
